spring:
  application:
    name: eureka
  profiles:
    active: dev
  security:
      basic:
        enabled: true
      user:
        name: admin
        password: admin


server:
  port: 8761
  servlet:
    context-path: /


eureka:
  server:
    enable-self-preservation: false # 测试时关闭自我保护机制，保证不可用服务及时踢出
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30     #每30秒会向Eureka Server发起Renew操作
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/
