server:
  port: 7999
# ????
logging:
  config: classpath:logback-spring.xml
spring:
  redis:
    host: 192.168.106.128
    port: 6379
    database: 1
    password:
    jedis:
      pool:
        max-active: 2000
      #?????????????????
        max-wait: -1
        min-idle: 200
        # ??????idel??????
        max-idle: 200


#spring:
#  redis:
#    #host: 10.2.13.6 #sentinel??????
#    #port: 5001 #sentinel??????
#    timeout: 10000
#    database: 0
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
#    sentinel:
#      master: mymaster
#      nodes:
#        - 192.168.106.128:6379
#        - 192.168.106.128:6379
#        - 192.168.106.128:6379